### ISSUE TITLE
lignes keyword dupliquée

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/chaineEditorialeSP#12]
Le yamlEditor duplique à la fin du yaml 2 lignes (vides par ailleurs) : 

```
keywords_fr: ''
keywords_en: ''
```

**Comment by ServanneMo** [comment]
Le doublon “keywords_fr” et “keywords_en” tout en bas du yaml n'est pas présent au début, il apparait dès lors que l'on rempli un controlled keyword.

**Comment by PookMook** [comment]
c'est pour les keywords non controllés, est-ce que ca duplique meme quand tu mets des keywords non controllés?

**Comment by PookMook** [comment]
ok, la dernière release est bonne et regle le soucis!

**Comment by lakonis** [comment]
Attention, le bug semble perdurer. @ServanneMo continue de l'observer.

**Comment by PookMook** [comment]
meme sur https://yaml.14159.ninja ? (si jamais, dans le doute maj+f5 pour hard refresh la page)
ps: il y avait effectivement un mixup entre keyword**s**_fr et keyword_fr !
