### ISSUE TITLE
YamlEditor : bug sur keywords

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/chaineEditorialeSP#15]
attention, depuis la dernière release, le yamlEditor produit `keywords_fr` au lieu de `keyword_fr`. 
Il ne produit pas les `keyword_en`.

Par ailleurs, la nouvelle interface pour les mots-clés est problématique, et les éditeurs (@ServanneMo ) souhaitent revenir à une interface qui distingue : mots-clé alignés (controlled keywords), mot-clés auteurs FR (keyword_fr) et mot-clés auteurs EN (keyword_en).
Il faudrait donc 3 champs distincts fonctionnant de la même manière que le champs actuels "Mots clés", sauf que les mots-clés auteurs FR et EN interrogeront à terme une autre source pour faire de l'autocomplétion que le fichier utilisé actuellement.

**Comment by ServanneMo** [comment]
Attention ! À régler avant d'intégrer à Stylo
