### ISSUE TITLE
pb inversion keywords vs controlled keywords

### ISSUE THREAD

**Issue by ServanneMo** [EcrituresNumeriques/chaineEditorialeSP#3]
Les controlled keywords sont pour les mots-clés de Sens public. Ils sont tout en haut de la liste dans le yaml. Les "keywords fr/en" qui apparaissent sous les résumés sont en fait les mots-clés souhaités par l'auteur. Il faudrait donc inverser.

**Comment by PookMook** [comment]
bien recu, par contre j'ai des url de la BNF pour ces mots clés, mais pas de uriRameau, idRameau, wikidata, je garde les données que j'ai ? 

exemple de donnée
 {
  "fr": "Espace public",
  "en": "Public space",
  "it": "Spazio pubblico",
  "url": "http://catalogue.bnf.fr/ark:/12148/cb12011791z/",
  "id": "FRBNF12011791",
  "term": "Space",
  "selected": false
 }

Ca donnerait soit
 - label : Espace Public
   url : "http://catalogue.bnf.fr/ark:/12148/cb12011791z/"
   id : FRBNF12011791
   term : Space

ou alors avec le label sur le mode spip "[fr]Espace public[en]Public space[it]Spazio pubblico" ?
