### ISSUE TITLE
Déplacer "Catégories"

### ISSUE THREAD

**Issue by ServanneMo** [EcrituresNumeriques/chaineEditorialeSP#5]
La catégorie apparait pour le moment dans les keywords (ceux de l'auteur, pas les controlled keywords). Il faudrait qu'elle apparaisse dans "typeArticle"

**Comment by PookMook** [comment]
je vois que typeArticle est une chaine de caractère, je mets les categories sous quelle forme ?
1. une liste
2. une chaine séparée par des virugles : Création, archive
3. une chaine séparée par autre chose ? à préciser
