### ISSUE TITLE
Métadonnées répétées en fin d'article

### ISSUE THREAD

**Issue by ServanneMo** [EcrituresNumeriques/chaineEditorialeSP#6]
Petit bogue: quand on fait la conversion (via pandoc) en html, toutes les métadonnées du yaml réapparaissent dans un paragraphe à la fin de l'article (voir img), entre le dernier paragraphe et les notes de bas de page.
![capture d ecran 2017-07-10 a 21 11 21](https://user-images.githubusercontent.com/14794908/28046836-78bba83e-65b4-11e7-8768-e6c6a2f811ea.png)
![capture d ecran 2017-07-10 a 21 11 43](https://user-images.githubusercontent.com/14794908/28046837-7dad1d0a-65b4-11e7-94c8-23d73ecce399.png)

**Comment by PookMook** [comment]
est-ce qu'elle apparaissent au bon endroit tout de même ?
Tu obtiens ca en telechargeant le fichier, ou en faisant un copié/collé?

**Comment by ServanneMo** [comment]
Ça c'était lié au --- 
Maintenant c'est réglé
