### ISSUE TITLE
Syntaxe yaml

### ISSUE THREAD

**Issue by ServanneMo** [EcrituresNumeriques/chaineEditorialeSP#7]
Manque --- au début et à la fin du yaml produit

**Comment by PookMook** [comment]
je peux les ajouter, mais c'est un peu étrange, normalement les --- marques les début et fin de document dans un meme fichier, la on en a un seul: https://fr.wikipedia.org/wiki/YAML#Caract.C3.A9ristiques
je peux les rajouter au moment de telecharger le fichier ou il les faut aussi dans l'éditeur ?

**Comment by ServanneMo** [comment]
Je viens de faire le test sans les --- au début, puis sans les --- à la fin et j'ai le même bug. Il a l'air de vouloir vraiment les deux. Tu peux les ajouter au moment de télécharger, ou bien dans l'éditeur, je dirais que ça n'a pas d'importance. Va au plus simple pour toi.
